### ISSUE TITLE
AlphaWallet iOS does not detect uploaded icons

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/iconassets#9]
https://github.com/AlphaWallet/iconassets/tree/master/0x7f5c764cbc14f9669b88837ca1490cca17c31607
https://github.com/AlphaWallet/iconassets/tree/master/0x350a791bfc2c21f9ed5d10980dad2e2638ffa7f6

**Comment by colourfreak** [comment]
![image](https://user-images.githubusercontent.com/51817359/152120414-9aa1dc0c-1109-4ca1-9919-d250a6ab5cae.png)

**Comment by colourfreak** [comment]
![image](https://user-images.githubusercontent.com/51817359/152120434-11f26325-6c30-46ff-9b9d-19c410362888.png)

**Comment by hboon** [comment]
@colourfreak should be fixed now. This was because iOS is currently transitioning from reading token icons with the chain overlay to a copy of the icons which doesn't have those overlays. I have updated that copy now, so should show up

**Comment by colourfreak** [comment]
The problem still exists.

**Comment by colourfreak** [comment]
https://github.com/AlphaWallet/iconassets/tree/master/0x7f5c764cbc14f9669b88837ca1490cca17c31607

**Comment by hboon** [comment]
Not on TestFlight yet. Next one.

Build 419 from over the weekend was the same as the appstore version + some TokenScript bug fixes.

**Comment by hboon** [comment]
But I have updated the branch used by the current app store version so it should show up. But it's just a snapshot, so if you upload the images again, it wouldn't take effect in the current app store version.

But it will be updated again once we have a new TestFlight and when that is on the app store. (and we'll be done with this out of sync problem. It's only because we had a snapshot to deal with removing the chain overlay)
